# Google Cloud Build configuration
# Automated CI/CD for Refugee Crisis Intelligence System

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/refugee-crisis-intelligence:$COMMIT_SHA', '.']
    id: 'build-image'

  # Step 2: Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/refugee-crisis-intelligence:$COMMIT_SHA']
    id: 'push-image'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'refugee-crisis-intelligence'
      - '--image=gcr.io/$PROJECT_ID/refugee-crisis-intelligence:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=900'
      - '--set-env-vars=GEMINI_API_KEY=${_GEMINI_API_KEY}'
    id: 'deploy-cloud-run'

# Store images
images:
  - 'gcr.io/$PROJECT_ID/refugee-crisis-intelligence:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/refugee-crisis-intelligence:latest'

# Deployment options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Substitutions (set these in Cloud Build triggers or via command line)
substitutions:
  _GEMINI_API_KEY: 'your-gemini-api-key'

timeout: '1200s'
